from __future__ import annotations

from typing import Dict, List

from .catalog import ChipDefinition
from .family_support import get_family_support
from .planner import PlanResult


# Map chip family to GCC -mcpu flag
_CPU_FLAGS: Dict[str, str] = {
    "STM32F1": "-mcpu=cortex-m3 -mthumb",
    "STM32F4": "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard",
    "STM32G4": "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard",
}

# Map chip family to linker script memory layout template
_LINKER_TEMPLATES: Dict[str, str] = {
    "STM32F1": "cortex-m3",
    "STM32F4": "cortex-m4",
    "STM32G4": "cortex-m4",
}

# Map family startup source from ARM asm to GCC asm file name convention
_STARTUP_GCC_MAP: Dict[str, str] = {
    "startup_stm32f103xb.s": "startup_stm32f103xb.s",
    "startup_stm32g431xx.s": "startup_stm32g431xx.s",
}


def render_makefile(
    plan: PlanResult,
    project_name: str,
    chip: ChipDefinition,
    hal_sources: List[str],
    app_sources: List[str],
    module_sources: List[str],
) -> str:
    support = get_family_support(chip.family)
    cpu_flags = _CPU_FLAGS.get(chip.family, "-mcpu=cortex-m3 -mthumb")

    c_defines = [
        "USE_HAL_DRIVER",
        chip.c_define,
    ]

    include_dirs = [
        "Core/Inc",
        "App/Inc",
        "Modules/Inc",
        "Drivers/CMSIS/Include",
        f"Drivers/CMSIS/Device/ST/{support.cmsis_device_dir}/Include",
        f"Drivers/{support.hal_driver_dir}/Inc",
        f"Drivers/{support.hal_driver_dir}/Inc/Legacy",
    ]

    c_sources: List[str] = [
        "Core/Src/main.c",
        "Core/Src/peripherals.c",
        f"Core/Src/{support.it_source}",
        f"Core/Src/{support.hal_msp_source}",
        f"Drivers/CMSIS/Device/ST/{support.cmsis_device_dir}/Source/Templates/{support.system_source}",
    ]

    for hal_src in hal_sources:
        c_sources.append(f"Drivers/{support.hal_driver_dir}/Src/{hal_src}")

    c_sources.append("App/Src/app_main.c")
    for src in app_sources:
        c_sources.append(f"App/Src/{src}")

    for src in module_sources:
        c_sources.append(f"Modules/Src/{src}")

    asm_source = f"Drivers/CMSIS/Device/ST/{support.cmsis_device_dir}/Source/Templates/gcc/{support.startup_source}"

    flash_size = chip.flash_kb * 1024
    ram_size = chip.ram_kb * 1024

    lines = [
        f"# Makefile for {project_name} (auto-generated by ChipWhisper)",
        f"# Target: {chip.name} ({chip.family})",
        "",
        "######################################",
        "# Toolchain",
        "######################################",
        "ifdef GCC_PATH",
        "PREFIX = $(GCC_PATH)/arm-none-eabi-",
        "else",
        "PREFIX = arm-none-eabi-",
        "endif",
        "",
        "CC = $(PREFIX)gcc",
        "AS = $(PREFIX)gcc -x assembler-with-cpp",
        "CP = $(PREFIX)objcopy",
        "SZ = $(PREFIX)size",
        "HEX = $(CP) -O ihex",
        "BIN = $(CP) -O binary -S",
        "",
        "######################################",
        "# Target",
        "######################################",
        f"TARGET = {project_name}",
        "",
        "######################################",
        "# Building variables",
        "######################################",
        "DEBUG = 1",
        "OPT = -Og",
        "",
        "######################################",
        "# Paths",
        "######################################",
        "BUILD_DIR = build",
        "",
        "######################################",
        "# Source files",
        "######################################",
        "C_SOURCES = \\",
    ]

    for i, src in enumerate(c_sources):
        suffix = " \\" if i < len(c_sources) - 1 else ""
        lines.append(f"  {src}{suffix}")

    lines.extend([
        "",
        "ASM_SOURCES = \\",
        f"  {asm_source}",
        "",
        "######################################",
        "# Compiler flags",
        "######################################",
        f"CPU = {cpu_flags}",
        "",
    ])

    defines_str = " ".join(f"-D{d}" for d in c_defines)
    includes_str = " ".join(f"-I{d}" for d in include_dirs)

    lines.extend([
        f"C_DEFS = {defines_str}",
        "",
        f"C_INCLUDES = {includes_str}",
        "",
        "ASFLAGS = $(CPU) -Wall -fdata-sections -ffunction-sections",
        "",
        "CFLAGS = $(CPU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections",
        "",
        "ifeq ($(DEBUG), 1)",
        "CFLAGS += -g -gdwarf-2",
        "endif",
        "",
        "CFLAGS += -MMD -MP -MF\"$(@:%.o=%.d)\"",
        "",
        "######################################",
        "# Linker flags",
        "######################################",
        f"LDSCRIPT = STM32_FLASH.ld",
        "",
        "LIBS = -lc -lm -lnosys",
        "LIBDIR =",
        "LDFLAGS = $(CPU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS)",
        "LDFLAGS += -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections",
        "",
        "######################################",
        "# Build rules",
        "######################################",
        "all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin",
        "",
        "OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))",
        "vpath %.c $(sort $(dir $(C_SOURCES)))",
        "",
        "OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))",
        "vpath %.s $(sort $(dir $(ASM_SOURCES)))",
        "",
        "$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)",
        "\t$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@",
        "",
        "$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)",
        "\t$(AS) -c $(ASFLAGS) $< -o $@",
        "",
        "$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile",
        "\t$(CC) $(OBJECTS) $(LDFLAGS) -o $@",
        "\t$(SZ) $@",
        "",
        "$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)",
        "\t$(HEX) $< $@",
        "",
        "$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)",
        "\t$(BIN) $< $@",
        "",
        "$(BUILD_DIR):",
        "\tmkdir -p $@",
        "",
        "######################################",
        "# Clean",
        "######################################",
        "clean:",
        "\t-rm -rf $(BUILD_DIR)",
        "",
        "######################################",
        "# Dependencies",
        "######################################",
        "-include $(wildcard $(BUILD_DIR)/*.d)",
        "",
    ])
    return "\n".join(lines)


def render_linker_script(chip: ChipDefinition) -> str:
    flash_origin = f"0x{chip.irom_start:08X}"
    flash_size = f"{chip.flash_kb}K"
    ram_origin = f"0x{chip.iram_start:08X}"
    ram_size = f"{chip.ram_kb}K"

    return f"""/* Linker script for {chip.name} (auto-generated by ChipWhisper) */
/* Flash: {chip.flash_kb}KB  RAM: {chip.ram_kb}KB */

/* Entry Point */
ENTRY(Reset_Handler)

/* Highest address of the user mode stack */
_estack = ORIGIN(RAM) + LENGTH(RAM);

/* Generate a link error if heap and stack don't fit into RAM */
_Min_Heap_Size = 0x200;
_Min_Stack_Size = 0x400;

MEMORY
{{
  RAM    (xrw) : ORIGIN = {ram_origin}, LENGTH = {ram_size}
  FLASH  (rx)  : ORIGIN = {flash_origin}, LENGTH = {flash_size}
}}

SECTIONS
{{
  .isr_vector :
  {{
    . = ALIGN(4);
    KEEP(*(.isr_vector))
    . = ALIGN(4);
  }} >FLASH

  .text :
  {{
    . = ALIGN(4);
    *(.text)
    *(.text*)
    *(.glue_7)
    *(.glue_7t)
    *(.eh_frame)

    KEEP(*(.init))
    KEEP(*(.fini))

    . = ALIGN(4);
    _etext = .;
  }} >FLASH

  .rodata :
  {{
    . = ALIGN(4);
    *(.rodata)
    *(.rodata*)
    . = ALIGN(4);
  }} >FLASH

  .ARM.extab :
  {{
    *(.ARM.extab* .gnu.linkonce.armextab.*)
  }} >FLASH

  .ARM :
  {{
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  }} >FLASH

  .preinit_array :
  {{
    PROVIDE_HIDDEN(__preinit_array_start = .);
    KEEP(*(.preinit_array*))
    PROVIDE_HIDDEN(__preinit_array_end = .);
  }} >FLASH

  .init_array :
  {{
    PROVIDE_HIDDEN(__init_array_start = .);
    KEEP(*(SORT(.init_array.*)))
    KEEP(*(.init_array*))
    PROVIDE_HIDDEN(__init_array_end = .);
  }} >FLASH

  .fini_array :
  {{
    PROVIDE_HIDDEN(__fini_array_start = .);
    KEEP(*(SORT(.fini_array.*)))
    KEEP(*(.fini_array*))
    PROVIDE_HIDDEN(__fini_array_end = .);
  }} >FLASH

  _sidata = LOADADDR(.data);

  .data :
  {{
    . = ALIGN(4);
    _sdata = .;
    *(.data)
    *(.data*)
    . = ALIGN(4);
    _edata = .;
  }} >RAM AT> FLASH

  . = ALIGN(4);
  .bss :
  {{
    _sbss = .;
    __bss_start__ = _sbss;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
    __bss_end__ = _ebss;
  }} >RAM

  ._user_heap_stack :
  {{
    . = ALIGN(8);
    PROVIDE(end = .);
    PROVIDE(_end = .);
    . = . + _Min_Heap_Size;
    . = . + _Min_Stack_Size;
    . = ALIGN(8);
  }} >RAM

  /DISCARD/ :
  {{
    libc.a(*)
    libm.a(*)
    libgcc.a(*)
  }}

  .ARM.attributes 0 : {{ *(.ARM.attributes) }}
}}
"""
